export {default as genIns1} from './generalInstructions/1.png'
export {default as genIns2} from './generalInstructions/2.png'
export {default as genIns3} from './generalInstructions/3.png'
export {default as genIns4} from './generalInstructions/4.png'
export {default as genIns5} from './generalInstructions/5.png'
export {default as genIns6} from './generalInstructions/6.png'
export {default as genIns7} from './generalInstructions/7.png'